language: r

sudo: required

r_binary_packages:
 - ggplot2
 - dplyr
 - car
 - sjmisc
 - ryouready

env:
 global:
   - CRAN: https://cran.rstudio.com

notifications:
  slack: tadaadata:I5XxVZ1gO6B1s0xTjPDQVw0t
