language: r
sudo: false
cache: packages

notifications:
  slack: tadaadata:I5XxVZ1gO6B1s0xTjPDQVw0t

env:
  global:
    - _R_CHECK_CRAN_INCOMING_=true
    - NOT_CRAN=false

r:
- oldrel
- release
- devel
