language: r

sudo: required

r_binary_packages:
 - ggplot2
 - dplyr
 - car

r_github_packages:
  - sjPlot/sjmisc
  - markheckmann/ryouready

env:
 global:
   - CRAN: https://cran.rstudio.com

notifications:
  slack: tadaadata:I5XxVZ1gO6B1s0xTjPDQVw0t
