language: r
sudo: required
env:
 global:
   - CRAN: http://cran.rstudio.com

r_binary_packages:
 - ggplot2
 - dplyr
 - car
 - devtools

r_github_packages:
 - sjPlot/sjmisc

notifications:
  slack: tadaadata:I5XxVZ1gO6B1s0xTjPDQVw0t
